### ISSUE TITLE
meta: rules wishlist

### ISSUE THREAD

**Issue by AlbertoCentonze** [AlbertoCentonze/natrix#4]
- [x] memory overexpansion
- [x] use @view on functions that don't modify the state
- [x] use @pure on a function that doesn't read the state
- [x] explicitly mark @internal functions as such
- [ ] code complexity (limit cyclomatic complexity)
- [x] constants naming conventions
- [ ] import - initialize/use - export should be sequential
- [x] unused imports
- [ ] unused constants
- [ ] unused functions from inline interface
- [x] unused vars
- [x] enforce decorator order
- [ ] naming convention for internal functions
- [x] reminder to remove print statements
- [ ] avoid magic numbers for array bounds, array accesses
- [ ] enforce a variable containing semver being available in every module
- [ ] no cross-module variable monkeypatching
- [ ] memory variable proximity
- [ ] var scope could be stricter
- [ ] incomplete or missing natspec
